### ISSUE TITLE
Allez joue !

### ISSUE THREAD

**Issue by marminthibaut** [cogitoTeam/IA_a_cognitive_approach#17]
Est-ce que quelqu'un pourrait commit le fichier RuleBase nécessaire à l'analyse ?

J'ai cette exception lors d'un coup : 

```
18:31:05,020 DEBUG AC:68 - percept reçu class agent.Percept$Choices
18:31:05,021 DEBUG AC:71 - percept de types choices
18:31:05,024 DEBUG Neo4jActiveMemory:79 - getting best valued RPBS
18:31:05,025 ERROR AC:78 - erreur lors de l'analyse
java.io.FileNotFoundException: RuleBase (Aucun fichier ou dossier de ce type)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:97)
    at java.io.FileReader.<init>(FileReader.java:58)
    at ac.analysis.inferenceEngine.KnowledgeBase.<init>(KnowledgeBase.java:83)
    at ac.analysis.AdvancedAnalysisEngine.runEngine(AdvancedAnalysisEngine.java:99)
    at ac.analysis.Analysis.analyse(Analysis.java:53)
    at ac.AC.perceptReaction(AC.java:74)
    at agent.Agent.react(Agent.java:168)
    at agent.Agent.act(Agent.java:115)
    at test.Test.main(Test.java:27)
```

**Comment by marminthibaut** [comment]
Oups désolé, il faut bien veiller à le mettre à la racine du projet eclipse (de l'endroit où est executé l'appli, dans le même répertoire que le dossier neo4j ;)

**Comment by marminthibaut** [comment]
Bon maintenant il me faut une base d'amorçage (il me dis "Pas de choix en mémoire".

Quelqu'un pourrait commiter une archive de la base bootstrapée ?

**Comment by sipi** [comment]
Y en a pas pour le moment je suis en train de créer une méthode dans AC pour boostrapé la mémoire.
